# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1
jobs:
  test:
    macos:
      xcode: 12.4
    steps:
      - checkout
      - run: fastlane scan
workflows:
  test_release:
    jobs:
      - test
     
